karenzibohscrumy/urls.py
from django.contrib.auth import urls
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.forms import UserCreationForm
from .views import *
app_name = 'karenzibohscrumy'
urlpatterns = [
    path('accounts/', include(urls)),
    path('accounts/signup/', sign_up, name='signup'),
    path('addgoal/', add_goal, name='add'),
    path('successpage/', TemplateView.as_view(template_name='karenzibohscrumy/successpage.html'), name='successpage'),
    path('movegoal/<int:goal_id>/',move_view, name='movegoal'), #ex:  /karenzibohscrumy/2/
    path('home/', home, name='home')
]

myscrumy/urls.py
from django.contrib import admin
from django.urls import path, include
# from karenzibohscrumy.views import  get_grading_parameters

urlpatterns = [
    path('karenzibohscrumy/', include(('karenzibohscrumy.urls'), namespace ='karenzibohscrumy')),
    path('websocket/', include(('websocket.urls'), namespace ='websocket')),    
    path('admin/', admin.site.urls),
]

karenzibohscrumy/models.py
from django.contrib.auth.models import User
from django.db import models
from django.forms import ModelForm
from django.forms import PasswordInput

# Create your models here.

class GoalStatus(models.Model):
    status_name = models.TextField(default=None)

    def __str__(self):
        return self.status_name


class ScrumyGoals(models.Model):
    goal_name = models.TextField(default=None)
    goal_id = models.IntegerField(default=None)
    created_by = models.TextField(default=None)
    moved_by = models.TextField(default=None)
    owner = models.TextField(default=None)
    user = models.ForeignKey(
        User, related_name='user_name', on_delete=models.PROTECT)
    goal_status = models.ForeignKey(GoalStatus, on_delete=models.PROTECT)

    def __str__(self):
        return self.goal_name


class ScrumyHistory(models.Model):
    moved_by = models.TextField(default=None)
    created_by = models.TextField(default=None)
    moved_from = models.TextField(default=None)
    moved_to = models.TextField(default=None)
    time_of_action = models.TextField(default=None)
    goal = models.ForeignKey(ScrumyGoals, on_delete=models.PROTECT)

    def __str__(self):
        return self.created_by


class SignUpForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username', 'password']
        widgets= {
            'password': PasswordInput()
        }

class CreateGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_name', 'user','goal_status']


class MoveGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_status']


class EditGoalForm(ModelForm):
    class Meta:
        model = ScrumyGoals
        fields = ['goal_status']

karenzibohscrumy/views.py
import random
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib.auth.models import Group
from django.contrib.auth.forms import authenticate
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
# from django.utila.decorators import method_decorator


from .models import *
# Create your views here.


@login_required(login_url="/karenzibohscrumy/accounts/login")
def home(request):
    users = User.objects.all()

    def get_by_status(status_name):
        goals = GoalStatus.objects.get(status_name=status_name)
        status_goals = goals.scrumygoals_set.all()
        return status_goals

    daily_goals = get_by_status("Daily Goal")
    weekly_goals = get_by_status("Weekly Goal")
    verify_goals = get_by_status("Verify Goal")
    done_goals = get_by_status("Done Goal")

    dictionary = {
        'users': users,
        'weekly_goals': weekly_goals,
        'daily_goals': daily_goals,
        'verify_goals': verify_goals,
        'done_goals': done_goals,
        'user': request.user,
        'role': request.user.groups.all()[0].name,
    }
    return render(request, 'karenzibohscrumy/home.html', dictionary)


def sign_up(request):
    form = SignUpForm()
    if request.method == 'POST':
        data = request.POST.dict()
        user = User.objects.create_user(
            data['username'], data['email'], data['password'])
        user.save()
        new_user = User.objects.get(username=data['username'])
        developer = Group.objects.get(name='Developer')
        developer.user_set.add(new_user)
        return HttpResponseRedirect('/karenzibohscrumy/successpage')
    else:
        form
    return render(request, 'registration/signup.html', {'form': form})


def login(request):
    return render(request, 'registration/login.html')


def move_view(request, goal_id):
    try:
        goal = ScrumyGoals.objects.get(goal_id=goal_id)

    except ScrumyGoals.DoesNotExist:
        context = {'error': 'A record with that goal id does not exist'}
        return render(request, 'karenzibohscrumy/exception.html', context)
    else:
        current_user = request.user
        group = current_user.groups.all()[0].name
        user = {
            'current_user': current_user,
            'group': group
        }
    if request.method == 'POST':
        form = MoveGoalForm(request.POST, instance=goal)
        goal = form.save(commit=False)
        data = request.POST.dict()
    #   print(data['goal_status'], group == 'Developer')
        goal_status = GoalStatus.objects.get(id=data['goal_status'])
        goal_status = str(goal_status)
        user = goal.user
        if group == 'Developer' and (goal_status == 'Done Goal' or current_user != user):
            ctx = {'error': 'Developers can only edit their own goals'}
            return render(request, 'karenzibohscrumy/exception.html', ctx)

        elif group == 'Quality Assurance':
            ctx = {}
            if current_user == user and goal_status == 'Weekly Goal':
                ctx['error'] = 'QA members can only move goals between daily, verify and done columns.'
                return render(request, 'karenzibohscrumy/exception.html', ctx)

            elif current_user != user and goal_status != 'Done Goal':
                ctx['error'] = 'QA members can only move other people\'s goals to the done column.'
                return render(request, 'karenzibohscrumy/exception.html', ctx)

        elif group == 'Owner' and user != current_user:
            ctx = {'error': 'Members of the Owner group can only edit their own goals'}
            return render(request, 'karenzibohscrumy/exception.html', ctx)

        goal.save()
        return HttpResponseRedirect('/karenzibohscrumy/home')

    form = MoveGoalForm(instance=goal)
    return render(request, 'karenzibohscrumy/movegoal.html', {'form': form})


@login_required
def add_goal(request):
    current_user = request.user
    group = current_user.groups.all()[0].name
    print(group)
    user = {
        'current_user': current_user,
        'group': group
    }
    if request.method == 'POST':
        form = CreateGoalForm(request.POST)
        goal = form.save(commit=False)
        data = request.POST.dict()
        print(data['goal_status'])
        goal_status = GoalStatus.objects.get(id=data['goal_status'])
        goal_status = str(goal_status)
        print(group in ['Developer', 'Quality Assurance'])
        # print(data['goal_status'] == '7')
        goal.moved_by = goal.user
        goal.created_by = goal.user
        goal.owner = goal.user
        username = goal.user
        if (group in ['Developer', 'Quality Assurance']) and (goal_status != 'Weekly Goal' or username != current_user):
            ctx = {
                'error': f'Members of the {group} group can only create weekly goals for themselves'}
            return render(request, 'karenzibohscrumy/exception.html', ctx)

        elif group == 'Owner' and goal_status != 'Weekly Goal':
            ctx = {'error': 'Members of the Owner group can only create weekly goals'}
            return render(request, 'karenzibohscrumy/exception.html', ctx)

        random_list = list(random.sample(range(1000, 9999), 10))
        random.shuffle(random_list)
        random_no = random_list[0]
        goal.goal_id = random_no
        goal.save()
        return HttpResponseRedirect('/karenzibohscrumy/home')

    form = CreateGoalForm()
    return render(request, 'karenzibohscrumy/addgoal.html', {'form': form})

karenzibohscrumy/templates/karenzibohscrumy/addgoal.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>New Goal</title>
</head>
<body>
  <form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="submit" />
  </form>
  <br />
  <a href="{% url 'karenzibohscrumy:home' %}">Home</a>
</body>
</html>

karenzibohscrumy/templates/karenzibohscrumy/exception.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>

<body>
    <p>{{error}}</p>
</body>

</html>

karenzibohscrumy/templates/karenzibohscrumy/home.html
<html>

<body>
    <div>
        <h3>{{user}}:  {{role}}</h3>
        <table>
            <tr>
                <th>User</th>
                <th>Weekly Goals</th >
                <th>Daily Goals</th>
                <th>Verify Goals</th>
                <th>Done Goals</th>
            </tr>
            {% for user in users %}
            <tr>
                <td>{{user}}</td>
                <td>{% for goal in weekly_goals%}
                        {%if goal.user.username == user.username%}
                        <a href ={% url 'karenzibohscrumy:movegoal' goal.goal_id  %}>{{goal}}, {{goal.goal_id}}</a>
                        {%endif%}    
                    {%endfor%}
                </td> 
                <td>{% for goal in daily_goals%}
                    {%if goal.user.username == user.username%}
                    <a href ={% url 'karenzibohscrumy:movegoal' goal.goal_id  %}>{{goal}}, {{goal.goal_id}}</a>
                    {%endif%}    
                {%endfor%}
                </td>
                <td>{% for goal in verify_goals%}
                    {%if goal.user.username == user.username%}
                    <a href ={% url 'karenzibohscrumy:movegoal' goal.goal_id  %}>{{goal}}, {{goal.goal_id}}</a>
                    {%endif%}    
                {%endfor%}
                </td>
                <td>{% for goal in done_goals%}
                    {%if goal.user.username == user.username%}
                    <a href ={% url 'karenzibohscrumy:movegoal' goal.goal_id  %}>{{goal}}, {{goal.goal_id}}</a>
                    {%endif%}    
                {%endfor%}
                </td>
            {% endfor %}
            </tr>
            
        </table>
    </div>
    <p> <a href ={% url 'karenzibohscrumy:add' %}>ADD A GOAL</a></p>
</body>

</html> 

karenzibohscrumy/templates/karenzibohscrumy/movegoal.html
<html>
    <body>
        <section>
            <h2>Move Goal</h2>
            <form method="POST"> {% csrf_token %}
                {{form}}
                <input type="submit">
            </form>
        </section>
    </body>
</html>        

karenzibohscrumy/templates/karenzibohscrumy/successpage.html
<html>
    <body>
        <p>Account created successfully!!!</p>
        <a href = {% url 'karenzibohscrumy:login'%}>Login to your account</a>
    </body>
</html>